### ISSUE TITLE
angular2 router not deactivated

### ISSUE THREAD

**Issue by daniele-zurico** [CanopyTax/single-spa-angular2#1]
Hi,
first of all great work!
I'm trying to use your example to see if this tool fit with my requirement and in the angular2 application I tried to add a simple router example. the angular 2 works great but when I try to switch to react (after angular2 has been loaded) it fail because angular2 is not unmounted and it try to find the path app1.

this is the repository that I created: https://github.com/daniele-zurico/microservice-test

**Comment by joeldenning** [comment]
See related https://github.com/angular/angular/issues/19079 and https://github.com/CanopyTax/single-spa/issues/115.

I think there is a bug in angular itself which is causing this.
