### ISSUE TITLE
No NgModule metadata found for 'AppModule'

### ISSUE THREAD

**Issue by mbanting** [CanopyTax/single-spa-angular2#2]
As always, thanks for the great framework and for putting together these starter kits.

I'm running into an error when attempting to use two Angular 2 based child apps that were implemented using the single-spa-angular2 starter kit. 
When I navigate from angularApp1 -> angularApp2 -> angularApp1
both apps mount and render successfully the first time, but when navigating back to angularApp1 I get the following error in the console. angularApp2 continues to mount and render fine.

```
Uncaught Error: 'angularApp1' died in status NOT_MOUNTED: No NgModule metadata found for 'AppModule'.
    at NgModuleResolver../node_modules/@angular/compiler/@angular/compiler.es5.js.NgModuleResolver.resolve (portal.bundle.js:19073)
    at CompileMetadataResolver../node_modules/@angular/compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (portal.bundle.js:19720)
    at JitCompiler../node_modules/@angular/compiler/@angular/compiler.es5.js.JitCompiler._loadModules (portal.bundle.js:31164)
    at JitCompiler../node_modules/@angular/compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (portal.bundle.js:31137)
    at JitCompiler../node_modules/@angular/compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (portal.bundle.js:31066)
    at PlatformRef_../node_modules/@angular/core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone (portal.bundle.js:36752)
    at PlatformRef_../node_modules/@angular/core/@angular/core.es5.js.PlatformRef_.bootstrapModule (portal.bundle.js:36738)
    at Array../src/portal.app.ts.mount (portal.bundle.js:64427)
    at i (vendor.bundle.js:29977)
    at vendor.bundle.js:2997
```

I can put together a sample project to demonstrate it but was wondering if you've seen this error before and have any ideas what's causing it? I'm more of a React dev so my knowledge of Angular isn't the best. Any help is appreciated!

**Comment by joeldenning** [comment]
Thanks for creating this issue and participating! And sorry it took me a couple of days to respond.

Could you provide a code sample or create a repo to help reproduce this? You could fork https://github.com/joeldenning/simple-single-spa-webpack-example as a place to start. It isn't  AngularJS and Angular2 coexist, but rather React and Angular. I'm curious if this is solely related to how you have configured the Angular app or if it has something to do with Angular detecting the AngularJS global variable and trying to do some magic with the dependency injection namespace. Is `AppModule` defined inside of Angular? Or is it in AngularJS?

**Comment by mbanting** [comment]
Hi there!

Following your suggestion, I forked the repo here: https://github.com/mbanting/simple-single-spa-webpack-example

- [_master_](https://github.com/mbanting/simple-single-spa-webpack-example) has a second Angular app added. Child apps are directly loaded via ES6 imports, as in the original repo. 

- The [_multiple-angular-webpack-systemjs_](https://github.com/mbanting/simple-single-spa-webpack-example/tree/multiple-angular-webpack-systemjs) branch adds to this by using Webpack to bundle each Angular child app and using SystemJS to import them. It also required moving the zone.js import to the parent app. 

#### Steps to reproduce:

- build and run as stated in the README
- in your browser, click App 1, App 2, App 3, then back to App 2

#### Expected behaviour:

- Each click results in the corresponding app loading successfully (this works in _master_, but not in _multiple-angular-webpack-systemjs_)


#### Actual behaviour:

- Each app is loaded successfully the first time they're loaded, but going back to App 2 after loading App 3 results in the error in the original post (this is what's happening in _multiple-angular-webpack-systemjs_)

Since it's working with direct Imports, this issue seems to be related to using Webpack to build the child apps and importing the bundle via SystemJS.

I realize this may not be an single-spa issue, and more of an Angular / Webpack / SystemJS type of thing, but any light that you can shed would be helpful for those that are using this combination with single-spa. Thank you!

**Comment by joeldenning** [comment]
Thanks, I'll take a look and see if I can find the problem and put together a fix.

**Comment by joeldenning** [comment]
@mbanting I fixed the issue and pull requested it into your forked repo. See https://github.com/mbanting/simple-single-spa-webpack-example/pull/1#pullrequestreview-64632075

**Comment by joeldenning** [comment]
Closing now, feel free to reopen if my fix doesn't work

**Comment by xeii** [comment]
I was able to solve this issue by excluding `reflect-metadata` when bundling child apps, and adding it as a common dependency on the root app side.

**Comment by joeldenning** [comment]
@xeii glad to hear you fixed it! To try and help others who also have multiple angular child applications, I added a note in the Readme for this: https://github.com/CanopyTax/single-spa-angular2/blob/master/README.md#other-notes
