### ISSUE TITLE
Cannot load an angular cli project with single-spa

### ISSUE THREAD

**Issue by Slash7GNR** [CanopyTax/single-spa-angular2#5]
Hey,
I've created a new project that gets a bundle.js file dynamically and loads it using single-spa and single-spa-angular2.
I could load a regular angular project and a vanilla JS project, but when I'm creating an angular cli project (using "ng new" angular cli command), building it and trying to load its bundle, I'm encountering errors when loading the bundle.js file (I'm using SystemJS.import for that).
I tried as well to configure the project's webpack config file (using ng eject) but nothing helped.
Do you have any step-by-step guide of how to use single-spa for angular cli project?
Hope my question is cleared and in the right place, it's the first time I'm asking here.

Thanks.

**Comment by joeldenning** [comment]
Could you provide the stacktrace you get when SystemJS tries to load the bundle?

**Comment by Slash7GNR** [comment]
So I've made some progress, and I still got some unsolved questions.
I have a project that get some JS that represents another project and it can load it into the browser. The source code of this project can be found [here](https://github.com/DanielKag/shell)
Now, I'm trying to make it load a real project we're having, but it was too complicated, so I wanted first to make it load an empty angular cli project, what I did so far:
1. Created an empty project using "ng new".
2. Since my project loads expect the JS to be in AMD format, I used "ng eject" to extract the web pack config.
3. In the web pack config, I've added to module.exports.output the "libraryTarget" property set to "AMD".
4. I wanted to load only one JS file(otherwise I've got errors while loading them), so I removed all the CommonPlugin section from the web pack config, so that I'll get only one bundle when building the project.
5. I ran "npm run build" and took the loaded the bundle file using the loader project.

**I'm facing the following problems:**
1. While running "npm run build" in the child app, I've got the following error:

> Error: Tried to find bootstrap code, but could not. Specify either statically analyzable bootstrap code or pass in an entryModule to the plugins options.

My main.ts file looks like this:
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

import singleSpaAngular2  from 'single-spa-angular2';

if (environment.production) {
  enableProdMode();
}

const mainModule = AppModule;

const ng2Lifecycles = singleSpaAngular2({
  domElementGetter,
  mainModule,
  angularPlatform: platformBrowserDynamic(),
  template: `<app-login />`,
})

export const bootstrap = [
  ng2Lifecycles.bootstrap,
];

export const mount = [
  ng2Lifecycles.mount,
];

export const unmount = [
  ng2Lifecycles.unmount,
];

function domElementGetter() {
  return document.getElementById('main-app');
}

To overcome this problem, I've added the following unreachable if statement which I don't like:

if (0 > 1) {
  platformBrowserDynamic().bootstrapModule(AppModule);
}

What can I do to fix this problem correctly?


2. I want to be able to run the child-app independently, but after making the above changes, I'm getting the following error in the browser, while running the child-app independently:
Uncaught ReferenceError: define is not defined
    at main.bundle.js:1


3. Before I removed the CommonPlugin from the web pack, the project was bundled splitting by the following bundles: vendor, inline, polyfills, styles and main bundle. I tried to load them one by one in the parent, with the following code: 
  applications
    .then(json => json.apps)  
    .then(apps => {
        apps.forEach(app => {
          declareChildApplication(app.name, 
                                  () => {
            if (app.name === 'login') {
                **SystemJS.import('./childApps/login/vendor.bundle.js');
                SystemJS.import('./childApps/login/inline.bundle.js');
                SystemJS.import('./childApps/login/polyfills.bundle.js');
                SystemJS.import('./childApps/login/styles.bundle.js');**
            }

            SystemJS.import(app.url)
        },
        isAppActive(app.name)
});
        })    
      });

but I've got the following error:
Uncaught Error: 'login' died in status LOADING_SOURCE_CODE: webpackJsonp is not defined
  Evaluating http://127.0.0.1:8080/childApps/login/main.bundle.js
  Loading ./childApps/login/main.bundle.js
    at eval (main.bundle.js:1)
    at i (system.js:4)
    at j (system.js:4)
    at O (system.js:4)
    at k (system.js:4)
    at system.js:4
    at ZoneDelegate.invoke (zone.js:390)
    at Zone.run (zone.js:142)
    at eval (zone.js:844)
    at ZoneDelegate.invokeTask (zone.js:423)



Thanks in advanced for your answer,

**Comment by joeldenning** [comment]
Thanks for the detailed explanation, that's very helpful.

#### First question
> Is it OK to leave it to bundle all to one file? Will it affect my app's performance?

That's a tricky question to answer definitively. The performance impact of code splitting is an area that a lot of frameworks and community members are actively exploring. From what I have seen, the currently accepted answer is that route-based code splitting is probably good in a lot of cases, and that non-route-based code splitting is sometimes good for performance, sometimes negligible, and sometimes even hurts performance.

I think two things to consider are the size of the child applications and whether you are supporting mobile. In production at Canopy, we have over ten child applications that are usually between 500k - 1.5mb bundles. We have done code splitting for one of them, but haven't for the rest of the child applications. And we have not seen adverse performance effects of loading bundles of that size for desktop users. If we had to support mobile, though, we might code split more aggressively.

All of that said, you *_can_* get code splitting working in your webpack bundles even when they are initially loaded by SystemJS. So it should be totally possible for you to turn code splitting on (we do this at Canopy and it works great). The `webpackJsonp is not defined` error is usually related to not executing the webpack entry bundle first before trying to load one of the code splits. In the example here at Canopy, our webpack config looks like this:

```js
/* eslint-env node */
let path = require('path');
let webpack = require('webpack');

module.exports = {
	entry: './src/global-settings.js',
	output: {
		filename: 'global-settings.js',
		library: 'global-settings',
		libraryTarget: 'amd',
		path: path.resolve(__dirname, 'sofe'),
	},
	module: {
		rules: [
			{
				test: /\.js?$/,
				exclude: [path.resolve(__dirname, 'node_modules')],
				loader: 'babel-loader',
			},
			{
				test: /\.css$/,
				use: [
					'style-loader',
					{
						loader: 'css-loader',
						options: {
							modules: true,
							localIdentName: '[path][name]__[local]'
						}
					}
				],
				exclude: [path.resolve(__dirname, 'node_modules')],
			},
			{
				test: /\.css$/,
				include: [path.resolve(__dirname, 'node_modules')],
				use: ['style-loader', 'css-loader']
			}
		]
	},
	plugins: [
		new webpack.optimize.CommonsChunkPlugin({
			filename: 'common.js',
			name: 'commons',
			minChunks: 2,
			children: true,
		})
	],
	devtool: 'source-map',
	externals: [
		/^.+!sofe$/,
		/^lodash$/,
		/^moment$/,
		/^prop-types$/,
		/^react$/,
		/^react-dom$/,
		/^rx$/,
		/^sofe$/,
	]
};
```

the global-settings.js bundle starts like this (notice how webpackJsonpglobal_settings is a global variable that is created):
```js
define("global-settings", ["react","canopy-urls!sofe","primary-navbar!sofe","cp-client-auth!sofe","lodash","canopy-styleguide!sofe","fetcher!sofe","react-dom","feature-toggles!sofe","rx","moment"], function(__WEBPACK_EXTERNAL_MODULE_0__, __WEBPACK_EXTERNAL_MODULE_5__, __WEBPACK_EXTERNAL_MODULE_7__, __WEBPACK_EXTERNAL_MODULE_8__, __WEBPACK_EXTERNAL_MODULE_11__, __WEBPACK_EXTERNAL_MODULE_12__, __WEBPACK_EXTERNAL_MODULE_27__, __WEBPACK_EXTERNAL_MODULE_35__, __WEBPACK_EXTERNAL_MODULE_44__, __WEBPACK_EXTERNAL_MODULE_119__, __WEBPACK_EXTERNAL_MODULE_135__) { return /******/ (function(modules) { // webpackBootstrap
/******/ 	// install a JSONP callback for chunk loading
/******/ 	var parentJsonpFunction = window["webpackJsonpglobal_settings"];
/******/ 	window["webpackJsonpglobal_settings"] = function webpackJsonpCallback(chunkIds, moreModules, executeModules) {
```

and then the code split bundles start like this (notice how they call the global variable created by global-settings.js):
```js
webpackJsonpglobal_settings([0],{

/***/ 100:
/***/ (function(module, exports, __webpack_require__) {

"use strict";


Object.defineProperty(exports, "__esModule", {
	value: true
});
```

#### Second question
```js
Uncaught Error: 'login' died in status NOT_MOUNTED: Unexpected value 'SharedModule' imported by the module 'LoginModule'. Please add a @NgModule annotation.
```

This is an Angular-specific error. The `'login' died in status NOT_MOUNTED` is single-spa wrapping an error that Angular threw, but the original error came from Angular. You can check out https://github.com/angular/angular/issues/15763 for some discussion on what "Please add a @NgModule annotation" might mean and how to fix it. One suggested solution was to `import 'reflect-metadata'` somewhere in your code if you're not already doing so. I am not an expert in Angular, myself, but am happy to try to help the best I can.

Thanks again for the details - hope this helps!

**Comment by Slash7GNR** [comment]
@joeldenning Thank you so much!
So indeed the import 'reflect-metadata' was missing, but the real problem is that I accidentally excluded some files from the bundling process(I thought that I merged everything into the main bundle, but I didn't), such as the polyfills.ts file which contains this import.
We will try to investigate how to bundle our code to multiple files with the help of the webpack config you've added.
We're right now making many researches for this task, can we leave this issue opened for now? I'm sure we'll have some more questions soon.

And again, thank you, it's very helpful!

**Comment by joeldenning** [comment]
👍  No problem! Definitely reach out if you have further problems or questions.

You can also check out the following issues for more discussion and resources related to code splitting:
- https://github.com/CanopyTax/single-spa/issues/102
- https://github.com/CanopyTax/single-spa/issues/125
- https://github.com/CanopyTax/single-spa/issues/123

**Comment by Slash7GNR** [comment]
Hey @joeldenning 
First of all I would like to thank you again for your willing to help! The single-spa framework and your support really helped us with many challenges we have had.

We have done some hands-on working in order to convert our applications to act as micro front-ends, under the single-spa framework. Moreover, we've done some brainstorming with our team and our architects, and we've got some questions.

**1.** I could successfully load an empty angular CLI application to my root application by refactoring it to load my child-app in the following way:
```
declareChildApplication(app.name,
                                      () => {
                                            return SystemJS.import('./childApps/ndv/inline.bundle.js')
                                                .then(() => SystemJS.import('./childApps/ndv/polyfills.bundle.js')
                                                    .then(() => SystemJS.import('./childApps/ndv/styles.bundle.js')
                                                        .then(() => SystemJS.import('./childApps/ndv/vendor.bundle.js')
                                                            .then(() => SystemJS.import('./childApps/ndv/main.bundle.js')))));
                                      },
                                      isAppActive(app.name));
```
Is it the way to do it ?

**2.** When I tried to load my real application, I'm getting the following error:
![image](https://user-images.githubusercontent.com/7475690/34214297-baf46bc0-e5aa-11e7-94da-3cd08f2832e2.png)
Do you have any idea what could cause the problem?
Let me know if you want me to attach any of the bundle files (inline, polyfills, styles, vendor, main), I didn't want to include them if it's unnecessary since they are pretty big.

**3.** We have global styles and each child-app has its own styles, but we don't know how to load the child app's styles (we're using SASS for styling), what is the best practice to load the child app's & global styles? (They should be compiled to CSS together since the child app's styles is using sass variables from the global styles).

**4.** We're facing some problems loading a child-app's own assets. The application searching for its relevant assets under the root application (although there are not found under the root application, and shouldn't be there). How can we load the child-app with its own assets, while those assets are being stored on the child app's folder?
Moreover, wouldn't we have a collision if two child-apps will have two assets in the same name ?

**5.** We have a requirement where two child-apps can be in different angular versions (for example, first app in angular version 2, and second app in angular version 4).
This requirement is mainly for easy framework upgrades (each child app is responsible for its own framework).
will it be a problem? if so, how can we overcome this ?

**6.** We've made some researches about micro front-ends, and found that one of the options to implement a micro front-end application is to use iframes, are you familiar with it? what are the pros and cons in comparison of using single-spa as a solution ?

**Comment by robinComa** [comment]
Hello, I try to use single sap in order to build a portal for my client.
This portal should work like the google button to switch between apps.

We want to build our application thanks to angular 5 but we want to keep the opportunity to work with react or view.js later so single spa seems perfect to perform this.

We want put all the apps inside a single git repository to manage a single lifecycle but we want stand-alone apps to develop and for the build.

I imagine create my apps thanks to ng new, develop it with ng serve inside the app repository, build it with ng build and aggregate it with root-application.js of single spa (we don't want be married with single spa ;-) ).

[This is my simple repository with one angular app created with ng new](https://github.com/PlaceMe-SAS/single-spa-as-microfrontends), my issues are : 

- First step : run the angular app with single-spa-angular2 : ko : 
`single-spa.js:1 Uncaught Error: 'app-1' died in status NOT_MOUNTED: "Failed to load app.component.html"`
And I have to change my imports : 
`import { AppComponent } from './app.component';`
should be 
`import { AppComponent } from './app.component.ts';`
- Second step (if I solve the first) : don't use single-spa-angular2 and use directly the bundle.js and * produce by the ng build : ko -> I manage to load one time the apps but when I remove it of the dom, I don't manage to reload it.

My conclusion is that single spa could not do it, but I'm not sure, could you help me?

Thanks by advance!

**Comment by rivamadan** [comment]
Hi @Slash7GNR,
I'm also trying to get angular (I'm using 5) to import with SystemJS and I think we've been facing similar problems. Maybe we can help each other out.

I wrote made this issue about what I've faced / am facing: https://github.com/CanopyTax/single-spa/issues/133
I haven't been able to get code splitting to work yet, but I am close to getting it to work with everything in one bundle.

**Comment by robinComa** [comment]
@Slash7GNR , I've forked the repo and add a sample here : 
https://github.com/PlaceMe-SAS/single-spa-examples
You have to run the npm run build task to generate the apps (inside the angular-mf folder)
I do "ng eject" and use AMD to build my angular app.
The simple spa loader use requirejs to load and run it

I have a last issue that I want to solve yet : when I run the apps, it take the control of the location changes and go out it is impossible.

Next step will be to externalize it : 
https://github.com/PlaceMe-SAS/single-spa-examples/tree/master/single-spa-angular-mf/src
and do an instance like the others single spa connector : 
https://github.com/PlaceMe-SAS/single-spa-examples/blob/master/src/angular-mf/angular-mf.app.js

Thanks for your webpack config file!

**Comment by area73** [comment]
Hi @Slash7GNR, @rivamadan , I also made a fork at https://github.com/area73/single-spa-examples/tree/feature/angular5-demo
And at the begining I had  the same issue with going to another route after entering my new angular 5 app but I solved it , I can't remember what exactly did but you can have a look at that repo into angular5 witch is were the app resides.
But I think when you fix that you will end up with the same issue that I have now and is that now after entering the angular5 app the view is not destroy. I report this  issue to @joeldenning  in this link
https://github.com/CanopyTax/single-spa-examples/issues/24

Because I think that the problem comes from single-spa-angular2 on unmount function.

We are almost there :) 👍

**Comment by joeldenning** [comment]
Glad to see you guys cooperating on this stuff! I'll take a look at https://github.com/CanopyTax/single-spa-examples/issues/24

**Comment by joeldenning** [comment]
Also we just created a gitter room for single-spa, which I will be in along with a few others from Canopy who have a lot of experience with single-spa. Feel free to join and collaborate further there. https://gitter.im/single-spa/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by robinComa** [comment]
Hi!

I just manage to load dynamicly a builded angular 5 project to integrate it inside the single SPA example. My exemple has 2 routes and one of it is a lazy loading of a module! (but not lazy loaded inside single SPA ;-)
It is possible to develop and serve with the cli and on a same time on single SPA. 
[The repo is here](https://github.com/PlaceMe-SAS/single-spa-examples)
[have a look on the cli projet readme](https://github.com/PlaceMe-SAS/single-spa-examples/tree/master/src/angular5-mf) to be able to run 
`npm run build:singleSpa`
or
`npm run serve:singleSpa`

It is a hack with a global object of window... sorry for that : 
[see the adapter for single spa for angular 5 ](https://github.com/PlaceMe-SAS/single-spa-examples/blob/master/single-spa-angular-mf/src/single-spa-angular-mf.js)
[And the code as the user of the adaptor](https://github.com/PlaceMe-SAS/single-spa-examples/blob/master/src/angular5-mf/loader.js)

For the moment, I removed zonejs from the app, so the app not able for the moment to up from the cli : [see polyfills l60](https://github.com/PlaceMe-SAS/single-spa-examples/blob/master/src/angular5-mf/src/polyfills.ts)

To conclude, no big impact for your angular 5 app, [only line 15](https://github.com/PlaceMe-SAS/single-spa-examples/blob/master/src/angular5-mf/src/main.ts), it is based on [this piece of code](https://github.com/PlaceMe-SAS/single-spa-examples/blob/master/single-spa-angular-mf/src/single-spa-angular-platform.ts). 

Last steps : 

- Load dynamically the scripts and css file name from the builded index.html to replace the file names [here](https://github.com/PlaceMe-SAS/single-spa-examples/blob/master/src/angular5-mf/loader.js) : L7 to L11 and remove this flags :  --output-hashing=media --extract-css=false

- Be ok with zonejs between multi angular apps

- Package all as a single spa plugin for microfrontend

Bye

**Comment by robinComa** [comment]
I just create a better impl with 2 angular apps lazy loaded and serve by the cli : 
[2 angular cli apps branch ](https://github.com/PlaceMe-SAS/single-spa-examples/tree/tech/multi_angular_mf_apps)

With a better impl of the chain angular cli loading : 
[bootstrap fn](https://github.com/PlaceMe-SAS/single-spa-examples/blob/tech/multi_angular_mf_apps/src/util/single-spa-angular-mf.js)

You have a full [documentation here](https://github.com/PlaceMe-SAS/single-spa-examples/tree/tech/multi_angular_mf_apps#this-project-is-an-angular-5-portal-as-microfrontend-lazy-loaded)

Is now possible to develop apps individually and on the portal at the same time : 

- Portal on port 8080

- Home on port 4200

- App1 on port 4201

TODO : 
automate this scripts array (maybe generate a json file on build process) : 
`const lifecycles = singleSpaAngularMicroFrontend({
    selector: 'app1-root',
    baseScriptUrl: 'http://localhost:4201',
    scripts: [
        'inline.bundle.js',
        'polyfills.bundle.js',
        'styles.bundle.js',
        'vendor.bundle.js',
        'main.bundle.js'
    ]
});`

**Comment by joeldenning** [comment]
@robinComa that's awesome! Especially the documentation!

Would you be interested in submitting a pull request to this project (single-spa-angular2) that adds your new documentation? Thanks for putting all of that together!

**Comment by robinComa** [comment]
Hello,

Yes, but I think it is not really the same apps, for the moment single-spa-angular2 do the compilation and mine not.
I thonk a new repo called single-spa-angular-mf (mf for micro frontend) will be better to have the choice between both.

What do you think? (I could do it at the end of this week inside my group name for the moment)

**Comment by robinComa** [comment]
Hello @joeldenning 
I'm happy if you like it!

**Global var :** 
It is me who create the global variable because since angular 2, angular want to remove global access.
I'm don't like this way to put up (and down) the application, but I didn't manage to find another solution.
It is [here](https://github.com/PlaceMe-SAS/single-spa-angular-cli/blob/master/src/single-spa-angular-cli-platform.ts#L17).

**Script inside head**
Very good idea! I change it thanks to you, at the start of my development I was curious to see whats append when I remove the script from the dom with innerHTML = '', but script run always.
Thanks for that : [here](https://github.com/PlaceMe-SAS/single-spa-angular-cli/blob/master/src/single-spa-angular-cli.js#L96)

**single-spa-angular-cli**
Good idea to rename it, thanks for that!
I create the lib [here](https://www.npmjs.com/package/single-spa-angular-cli), and the repo is [here](https://github.com/PlaceMe-SAS/single-spa-angular-cli)
No problem to maintain it, and to adding you (and somebody who want to help us) as administrator.
If you are interresting say it ;-)

**Utils.js**
I choose to create [utils.js](https://github.com/PlaceMe-SAS/single-spa-angular-cli/blob/master/src/utils.js) file to help us to routing our application and put together 2 application at same time, that the case of the "menu" app with "home" app for example : [example here](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples/blob/master/src/main.js)
The an example is available [here](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples) with 3 apps : 
- Menu (display everitime)
- Home (with router and sub module lazy loaded)
- App1 (simple app)

**Next steps**
- [ ] real lazy loading of sub module (remove it from [here](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples/blob/master/src/home/loader.js#L11))
- [ ] Generate files list automaticly from the build task, to enable hash for build files (to avoid caching issues)

It is now possible to build your angular cli apps as microfrontend apps and deploy it on the fly (on a CDN for example) without redeploy the main single spa app.

**Comment by joeldenning** [comment]
Awesome! Thanks for all the work. I will add links to single-spa-angular-cli and single-spa-angular-cli-examples to the readme here at single-spa-angular2 and [in the single-spa docs for frameworks](https://github.com/CanopyTax/single-spa/blob/master/docs/single-spa-ecosystem.md#help-for-frameworks).

@Slash7GNR @area73 have you seen @robinComa's work on this? Does it work well for you guys, too?

**Comment by area73** [comment]
@joeldenning I haven't got time to check it deep but looks promising to me :)

**Comment by joeldenning** [comment]
I'm going to close this for now -- feel free to comment and reopen with further discussion. Hopefully [@robinComa's repo](https://github.com/PlaceMe-SAS/single-spa-angular-cli) will prove useful for people using angular-cli
